# Generated by Django 3.2.8 on 2021-12-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwordc',
            new_name='password',
        ),
    ]
